{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ default "2020" .Values.metrics.port }}
      targetPort: {{ default "2020" .Values.metrics.port }}
      protocol: TCP
  selector:
    {{- include "cloudflare-tunnel.selectorLabels" . | nindent 4 }}
{{- end }}
