apiVersion: v2
name: cloudflare-tunnel
description: "Creation of a cloudflared deployment : a reverse tunnel for an environment or a remotely managed tunnel that has already been provisioned in Cloudflare."
type: application
version: 0.5.0
appVersion: "2025.11.1"
icon: https://cf-assets.www.cloudflare.com/slt3lc6tev37/1nqjMDEcpKmpQqRZo1Ze11/91b60383b9459d519e81552351c3ea81/Hero-blade.svg
