apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}
data:
  config.yaml: |-
    no-autoupdate: true
    log-level: {{ default "info" .Values.logLevel }}
    protocol: {{ default "auto" .Values.protocol }}
    {{- if .Values.metrics.enabled }}
    # Serves the metrics server under /metrics and the readiness server under /ready
    metrics: 0.0.0.0:{{ default "2020" .Values.metrics.port }}
    {{- end }}
    {{- if eq .Values.configurationSource "remote" }}
    token-file: /etc/cloudflared/secrets/tunnelToken
    {{- else }}
    # Name of the tunnel you want to run
    tunnel: {{ .Values.local.tunnelName }}
    # The location of the secret containing the tunnel credentials
    credentials-file: /etc/cloudflared/secrets/credentials.json
    # General purpose TCP routing for the network
    warp-routing:
      enabled: {{ .Values.local.enableWarp }}
    # The `ingress` block tells cloudflared which local service to route incoming
    # requests to : https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
    ingress:
      {{- with .Values.local.ingress }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      # This rule matches any traffic which didn't match a previous rule, and responds with HTTP 404.
      {{- if .Values.local.enableDefault404 }}
      - service: http_status:404
      {{- end }}
    {{- end }}
