{{- if not .Values.local.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
stringData:
  {{- if eq .Values.configurationSource "local" }}
  credentials.json: |-
    {
      "AccountTag": {{ .Values.local.accountId | quote }},
      "TunnelID": {{ .Values.local.tunnelId | quote }},
      "TunnelSecret": {{ .Values.local.tunnelSecret | quote }}
    }
  {{- else }}
  tunnelToken: |-
    {{ .Values.remote.tunnelToken }}
  {{- end }}
{{- end }}
