apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 2020
      targetPort: 2020
      protocol: TCP
  selector:
    {{- include "cloudflare-tunnel.selectorLabels" . | nindent 4 }}
